In [1]:
import numpy as np 

1. Tạo dữ liệu mô phỏng

In [2]:
np.random.seed(45)
nhiet_do = np.round(np.random.uniform(low=15.0, high=35.0, size=30), 2)
nhiet_do

array([34.78, 25.99, 20.63, 16.55, 23.89, 24.46, 15.97, 18.27, 17.32,
       27.55, 32.12, 28.  , 34.81, 24.41, 27.37, 20.65, 34.52, 28.46,
       23.81, 20.79, 25.19, 17.25, 19.54, 24.57, 19.86, 22.76, 31.38,
       16.49, 33.46, 19.5 ])

Nhiệt độ trung bình


In [3]:
print("Nhiệt độ trung bình trong tháng:", nhiet_do.mean())

Nhiệt độ trung bình trong tháng: 24.345000000000002


2. Phân tích xu hướng nhiệt độ

In [4]:
print("Nhiệt độ cao nhất trong ngày:", nhiet_do.max())
print("Nhiệt độ thấp nhất trong ngày:", nhiet_do.min())
print("Ngày có nhiệt độ cao nhất:", nhiet_do.argmax() +1 )
print("Ngày có nhiệt độ thấp nhất:", nhiet_do.argmin() +1)

Nhiệt độ cao nhất trong ngày: 34.81
Nhiệt độ thấp nhất trong ngày: 15.97
Ngày có nhiệt độ cao nhất: 13
Ngày có nhiệt độ thấp nhất: 7


Thống kê sự chênh lệch nhiệt độ


In [5]:
#tạo mảng chứa nhiệt độ ngày hôm trước (trừ ngày cuối cùng)
ngay_truoc = nhiet_do[:-1]

#Tạo mảng chứa nhiệt độ ngày hôm sau (trừ ngày đầu)
ngay_sau = nhiet_do[1:]

#Tính toán sự chênh lệch nhiệt độ giữa ngày hôm sau và ngày hôm trước
chenh_lech = ngay_sau - ngay_truoc

#Xác định ngày có sự chênh lệch nhiệt độ lớn nhất
dff_max = chenh_lech.argmax() +1  # + 1 vì ngày đầu tiên bắt đầu từ 1
max_chenh_lech = chenh_lech[dff_max - 1]

print("Chênh lệch nhiệt độ cao nhất là:", max_chenh_lech)
print("Ngày chênh lệch cao nhất", dff_max)

Chênh lệch nhiệt độ cao nhất là: 16.970000000000002
Ngày chênh lệch cao nhất 28


3. Áp dụng Fancy Indexing


a. Tất cả các ngày có nhiệt độ cao hơn 20 độ


In [6]:
#Kiểm tra điều kiện nhiệt độ cao hơn 20 độ C
condition = nhiet_do > 20

#Sử dụng np.where để tìm chỉ số của các phần tử thỏa mãn điều kiện
indices = np.where(condition)

#Lấy chỉ số đầu tiên (vì np.where trả về tuple)
day_indices = indices[0]

#Chỉnh chỉ số để phù hợp với đánh số ngày (bắt đầu)
day_above_20_separated = day_indices + 1 

day_above_20_separated


array([ 1,  2,  3,  5,  6, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       24, 26, 27, 29], dtype=int64)

b. Lấy nhiệt độ của ngày 5, 10, 15, 20, 25

In [7]:
ngay = [5, 10, 15, 20, 25]
nhiet_do_ngay = nhiet_do[np.array(ngay) - 1] # -1 vì chỉ số python bắt đầu từ 0
print("Nhiệt độ của các ngày 5, 10, 15, 20, 25:")
print(nhiet_do_ngay)

Nhiệt độ của các ngày 5, 10, 15, 20, 25:
[23.89 27.55 27.37 20.79 19.86]


c. Tìm nhiệt độ các ngày có nhiệt độ trên trung bình


In [8]:
tren_tb = np.where(nhiet_do > nhiet_do.mean())[0] + 1
print("Các ngày có nhiệt độ trên trung bình:")
print(tren_tb)

Các ngày có nhiệt độ trên trung bình:
[ 1  2  6 10 11 12 13 14 15 17 18 21 24 27 29]


d. Lấy nhiệt độ các ngày chẵn/ lẻ gtrong tháng

In [9]:
ngay_chan = nhiet_do[1::2] #ngày chẵn: bắt đầu từ index 1 (ngày 2) và nhảy 2 bước
ngay_le = nhiet_do[0::2] #Ngày lẻ: bắt đầu từ index 0 (ngày 1) và nhảy 2 bước
print("Nhiệt độ ngày chẵn:")
print(ngay_chan)

print("\n Nhiệt độ ngày lẻ:")
print(ngay_le)

Nhiệt độ ngày chẵn:
[25.99 16.55 24.46 18.27 27.55 28.   24.41 20.65 28.46 20.79 17.25 24.57
 22.76 16.49 19.5 ]

 Nhiệt độ ngày lẻ:
[34.78 20.63 23.89 15.97 17.32 32.12 34.81 27.37 34.52 23.81 25.19 19.54
 19.86 31.38 33.46]
