In [2]:
import csv
import numpy as np 

In [3]:
file_path = "D:\\Năm 2 (2024 - 20250\\Python nâng cao\\Bài tập\\LAB2\\DATA\\diem_hoc_phan.csv"
data = []

with open(file_path, newline = '', encoding='utf-8') as csvfile:
    reader = csv.reader(csvfile)
    next(reader) #Bỏ qua hàng đầu tiên (Tiêu đề cột)
    '''
    Xử lý dữ liệu từ mỗi hàng: Với mỗi hàng row trong file csv,
    code sẽ lấy phần tử từ chỉ số 2 trở đi
    Điều này tương ứng với việc bỏ qua cột
    '''

    for row in reader:
        #Chuyeernd dổi điểm số từ string sang float
        data.append([float(score) for score in row[2:]])

#Hiển thị 5 dòng đầu
print(data[:5])


[[3.04, 3.39, 6.7], [5.8, 6.41, 6.62], [2.59, 3.57, 9.16], [3.81, 8.78, 9.24], [8.91, 9.64, 6.39]]


2. Qui đổi điểm tín chỉ


In [4]:

print(data)
diem_hp_array = np.array(data)
diem_hp_array[:5]


[[3.04, 3.39, 6.7], [5.8, 6.41, 6.62], [2.59, 3.57, 9.16], [3.81, 8.78, 9.24], [8.91, 9.64, 6.39], [3.23, 4.72, 6.17], [2.35, 3.29, 6.89], [2.48, 3.81, 4.84], [3.23, 2.61, 4.52], [7.02, 9.01, 9.15], [2.29, 4.48, 5.51], [3.51, 7.19, 5.13], [6.74, 7.78, 6.19], [9.86, 4.64, 3.33], [8.04, 5.12, 4.77], [2.74, 8.88, 5.8], [3.04, 6.88, 3.91], [5.87, 4.41, 8.84], [8.46, 2.63, 4.91], [3.74, 6.71, 3.44], [5.67, 8.05, 6.03], [8.12, 2.46, 3.87], [9.4, 5.31, 5.13], [3.91, 5.09, 8.82], [4.26, 5.78, 8.14], [4.41, 2.66, 5.4], [3.23, 8.3, 8.64], [9.25, 8.29, 9.1], [6.08, 2.67, 6.39], [3.85, 7.71, 5.75]]


array([[3.04, 3.39, 6.7 ],
       [5.8 , 6.41, 6.62],
       [2.59, 3.57, 9.16],
       [3.81, 8.78, 9.24],
       [8.91, 9.64, 6.39]])

In [5]:
def chuyen_diem(score):
    """Chuyển đổi điểm số sang điểm chữ theo tiêu chí đã cho"""
    if 8.5 <= score <= 10:
        return "A"
    elif 8.0 <= score < 8.5:
        return "B+"
    elif 7.0 <= score < 8.0:
        return "B"
    elif 6.5 <= score < 7.0:
        return "C+"
    elif 5.5 <= score < 6.0:
        return "C"
    elif 5.0 <= score < 5.5:
        return "D+"
    elif 4.0 <= score < 5.0:
        return "D"
    else:
        return "F"
#Áp dụng hàm quy đổi cho mõi điểm số trong mảng
diem_converted = np.vectorize(chuyen_diem)(diem_hp_array)

diem_converted[:5]

array([['F', 'F', 'C+'],
       ['C', 'F', 'C+'],
       ['F', 'F', 'A'],
       ['F', 'A', 'A'],
       ['A', 'A', 'F']], dtype='<U2')

Chia tách dữ liệu để phân tích điểm số của mỗi học phần riêng biệt

In [6]:
hp1_scores = diem_hp_array[:, 0]
hp2_scores = diem_hp_array[:, 1]
hp3_scores = diem_hp_array[:, 2]

In [7]:
diem_hp_array[:5]


array([[3.04, 3.39, 6.7 ],
       [5.8 , 6.41, 6.62],
       [2.59, 3.57, 9.16],
       [3.81, 8.78, 9.24],
       [8.91, 9.64, 6.39]])

In [8]:
hp1_scores

array([3.04, 5.8 , 2.59, 3.81, 8.91, 3.23, 2.35, 2.48, 3.23, 7.02, 2.29,
       3.51, 6.74, 9.86, 8.04, 2.74, 3.04, 5.87, 8.46, 3.74, 5.67, 8.12,
       9.4 , 3.91, 4.26, 4.41, 3.23, 9.25, 6.08, 3.85])

Phân tích dữ liệu điểm số cho mỗi học phần


In [9]:
hp1_stats = (np.sum(hp1_scores), np.mean(hp1_scores), np.std(hp1_scores))
hp2_stats = (np.sum(hp2_scores), np.mean(hp2_scores), np.std(hp2_scores))
hp3_stats = (np.sum(hp3_scores), np.mean(hp3_scores), np.std(hp3_scores))

In [10]:
print(hp1_stats)

(154.92999999999998, 5.1643333333333326, 2.4078519934211533)


In [11]:
print("Học phần 1:")
print(f"Tổng điểm: {hp1_stats[0]:.2f}")
print(f"Điểm trung bình: {hp1_stats[1]:.2f}")
print(f"Độ lệch chuẩn: {hp1_stats[2]:.2f}")

Học phần 1:
Tổng điểm: 154.93
Điểm trung bình: 5.16
Độ lệch chuẩn: 2.41


In [12]:
print("Học phần 2:")
print(f"Tổng điểm: {hp2_stats[0]:.2f}")
print(f"Điểm trung bình: {hp2_stats[1]:.2f}")
print(f"Độ lệch chuẩn: {hp2_stats[2]:.2f}")

Học phần 2:
Tổng điểm: 170.27
Điểm trung bình: 5.68
Độ lệch chuẩn: 2.25


In [13]:
print("Học phần 3:")
print(f"Tổng điểm: {hp3_stats[0]:.2f}")
print(f"Điểm trung bình: {hp3_stats[1]:.2f}")
print(f"Độ lệch chuẩn: {hp3_stats[2]:.2f}")

Học phần 3:
Tổng điểm: 188.78
Điểm trung bình: 6.29
Độ lệch chuẩn: 1.81


4. Phân tích tổng quan cho toàn bộ lớp học


In [14]:
#Tính toán cho toàn lớp
tong_diem_all = np.sum(diem_hp_array)
diem_tb_all = np.mean(diem_hp_array)
std_deviation_all = np.std(diem_hp_array)

tong_diem_all, diem_tb_all, std_deviation_all

(513.98, 5.710888888888889, 2.2185594146975665)

In [15]:
print("Tổng điểm của toàn lớp (cho tất cả học phần):", tong_diem_all)
print("Điểm trung bình của toàn lớp (cho tất cả học phần):", diem_tb_all)
print("Độ lệch chuẩn của toàn lớp:", std_deviation_all)

Tổng điểm của toàn lớp (cho tất cả học phần): 513.98
Điểm trung bình của toàn lớp (cho tất cả học phần): 5.710888888888889
Độ lệch chuẩn của toàn lớp: 2.2185594146975665
