In [2]:
import numpy as np

1


In [3]:
arr = np.full((3, 3), True)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

2

In [7]:
arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_1D 
arr_2D = arr_1D.reshape((3, 3))
arr_2D 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
arr_2D[:, [0,2]] = arr_2D[:, [2, 0]]
arr_2D


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [12]:
arr_2D[:, [2, 0]] = arr_2D[:, [0,2]]
arr_2D

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
arr_2D_a = np.flipud(arr_2D)
arr_2D_a

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [15]:
arr_2D_b = np.fliplr(arr_2D)
arr_2D_b

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [17]:
arr_2D_null = np.array([[1,2,3], [np.NaN, 5,60], [7,np.NaN,9],[4,5,6]])
a = np.any(np.isnan(arr_2D_null))
if a:
    print("Có giá trị rỗng.")
else:
    print("Không có giá trị rỗng.")

Có giá trị rỗng.


In [18]:
arr_2D = np.nan_to_num(arr_2D_null, nan=0)
arr_2D

array([[ 1.,  2.,  3.],
       [ 0.,  5., 60.],
       [ 7.,  0.,  9.],
       [ 4.,  5.,  6.]])